### ISSUE TITLE
[Feature Request] Create logger builders from existing loggers

### ISSUE THREAD

**Issue by Lancern** [SpriteOvO/spdlog-rs#13]
When using loggers in libraries, a common pattern is to build a new `Logger` object based on the global default logger with the logger's name changed and use that new `Logger` object as the dedicated logger for the library. However, currently it's difficult to implement similar logic because it's too tedious to build a new logger based on another logger:

```rust
pub fn init_my_library() {
    let mut library_logger_builder = LoggerBuilder::new();
    let default_logger = spdlog::default_logger();

    let library_logger = library_logger_builder
        .flush_level_filter(default_logger.flush_level_filter())
        .level_filter(default_logger.level_filter())
        .name("my library")
        .sinks(default_logger.sinks().cloned());
}
```

I suggest we add a new method to create `LoggerBuilder`:

```rust
impl LoggerBuilder {
    pub fn new_from_logger(logger: &Logger) -> Self;
}
```

The `new_from_logger` function creates a new `LoggerBuilder` object and copies all logger properties (name, log level, sinks, etc.) from the given logger to the new `LoggerBuilder` object. With this new method, library authors can easily create a dedicated logger for their own libraries and components:

```rust
pub fn init_my_library() {
    let library_logger = LoggerBuilder::new_from_logger(&*spdlog::default_logger())
        .name("my library")
        .build();
}
```

**Comment by Lancern** [comment]
At the very least we should simplify the procedure to create new loggers based on the default logger providing a different name. It's a very common practice for library authors.

**Comment by SpriteOvO** [comment]
Interesting suggestion, which involves some details to consider.

First, there is actually a simpler way to do this than your first example.

```rust
let mut new_logger = spdlog::default_logger().deref().clone();
new_logger.set_name(Some("new name"));
```

(`Logger::set_name` here does not currently exist, I just forgot it XD, and implement it is easy)

Based on this, we need to reconsider the need for a shorthand method. I don't completely reject your proposal, but we need to figure out the following questions:

- In the current implementation, in order to implement *periodic flushing*, the receiver of `set_flush_period` is `&Arc<Self>` ([code](https://github.com/SpriteOvO/spdlog-rs/blob/da3733d370d855ba5ff018129e753c43d115f2de/spdlog/src/logger.rs#L192)).

  `LoggerBuilder` returns `Logger` instead of `Arc<Logger>`, so it's not possible for `Logger::new_from_logger` to exactly replicate all the arguments of a logger (*periodic flushing* will not work on the new logger, if the old logger set it).

  Neither can my example above, which would cause a panic at runtime if a flush period is set ([code](https://github.com/SpriteOvO/spdlog-rs/blob/da3733d370d855ba5ff018129e753c43d115f2de/spdlog/src/logger.rs#L281-L305)). So along with `set_name`, a `try_clone` may also need to be implemented.

- So it should be possible to implement a
  ```rust
  Logger::clone_with(self: &Arc<Self>, modifier: impl FnOnce(&mut Logger)) -> Arc<Logger>
  ```
  , and it will be used in this way:

  ```rust
  let new_logger = spdlog::default_logger().clone_with(|new| new.set_name("new logger"));
  ```

  Compared to the above code, it is just one less line. However, since it serves only `Arc<Logger>`, it should be able to replicate all arguments (although users cannot modify the flush period in the closure).

- Further, I think that if we can somehow implement the receiver of `set_flush_period` as `&Logger` instead of the current `&Arc<Logger>`, and it doesn't cost much (e.g. performance, interoperability, etc.), then my first example is short enough and should be able to replicate all the arguments, so we don't need a `clone_with` shorthand, which is probably the best.

**Comment by Lancern** [comment]
I reconsidered the problem a little bit, and IMO all properties on the logger are not interesting to the library code in the majority of cases, except for the logger's name. So maybe what we lack here is just a clone_with_name method on the logger?在 2022年10月2日，19:03，Sprite ***@***.***> 写道：﻿
Interesting suggestion, which involves some details to consider.
First, there is actually a simpler way to do this than your first example.
let mut new_logger = spdlog::default_logger().deref().clone();
new_logger.set_name(Some("new name"));
(Logger::set_name here does not currently exist, I just forgot it XD, and implement it is easy)
Based on this, we need to reconsider the need for a shorthand method. I don't completely reject your proposal, but we need to figure out the following questions:


In the current implementation, in order to implement periodic flushing, the receiver of set_flush_period is &Arc<Self> (code).
LoggerBuilder returns Logger instead of Arc<Logger>, so it's not possible for Logger::new_from_logger to exactly replicate all the arguments of a logger (periodic flushing will not work on the new logger, if the old logger set it).
Neither can my example above, which would cause a panic at runtime if a flush period is set (code). So along with set_name, a try_clone may also need to be implemented.


So it should be possible to implement a
Logger::clone_with(self: &Arc<Self>, modifier: impl FnOnce(&mut Logger)) -> Arc<Logger>
, and it will be used in this way:
let new_logger = spdlog::default_logger().clone_with(|new| new.set_name("new logger"));
Compared to the above code, it is just one less line. However, since it serves only Arc<Logger>, it should be able to replicate all arguments (although users cannot modify the flush period in the closure).


Further, I think that if we can somehow implement the receiver of set_flush_period as &Logger instead of the current &Arc<Logger>, and it doesn't cost much (e.g. performance, interoperability, etc.), then my first example is short enough and should be able to replicate all the arguments, so we don't need a clone_with shorthand, which is probably the best.

**Comment by SpriteOvO** [comment]
`clone_with_name` should not be too different from `clone_with`, its function signature also requires the same receiver `&Arc<Logger>` and the same return type `Arc<Logger>`. I prefer `clone_with` because it provides more interoperability, so that in addition to downstream library code, downstream binary code will also benefit, as downstream binary code will be particularly interested in properties such as `sinks`.

**Comment by Lancern** [comment]
I suggest we add both of `clone_with` and `clone_with_name`, and make `clone_with_name` a convenient wrapper around `clone_with`.

**Comment by SpriteOvO** [comment]
> I suggest we add both of `clone_with` and `clone_with_name`, and make `clone_with_name` a convenient wrapper around `clone_with`.

Agree with that, I will open a PR later :)
